In [178]:
import pickle
import pandas as pd
import numpy as np

In [179]:
with open('knn_imputer.pkl','rb') as file:
    knn_imputer=pickle.load(file)

with open('simple_imputer.pkl','rb') as file:
    simple_imputer=pickle.load(file)

with open('encoders.pkl','rb') as file:
    encoders=pickle.load(file)

with open('scalar.pkl','rb') as file:
    scaler=pickle.load(file)

with open('random_forest_model.pkl','rb') as file:
    rfmodel=pickle.load(file)

In [180]:
input_data={
"age":48,
"blood_pressure":80,
"specific_gravity":1.02,
"albumin":1,
"sugar":0,
"red_blood_cells":"normal",
"pus_cell":"normal",
"pus_cell_clumps":"notpresent",
"bacteria":"notpresent",
"blood_glucose_random":121,
"blood_urea":36,
"serum_creatinine":1.2,
"sodium":0,
"potassium":0,
"hemoglobin":15.4,
"packed_cell_volume":44,
"white_blood_cell_count":7800,
"red_blood_cell_count":5.2,
"hypertension":"yes",
"diabetes_mellitus":"yes",
"coronary_artery_disease":"no",
"appetite":"good",
"pedal_edema":"no",
"anemia":"no",
}

In [181]:
input_df=pd.DataFrame([input_data])
input_df

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,hemoglobin,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia
0,48,80,1.02,1,0,normal,normal,notpresent,notpresent,121,...,15.4,44,7800,5.2,yes,yes,no,good,no,no

In [182]:
cat=[]
num=[]
for i in input_df.columns:
    if input_df[i].dtype=="object":
        cat.append(i)
    else:
        num.append(i)
print(cat) 
print(num)

['red_blood_cells', 'pus_cell', 'pus_cell_clumps', 'bacteria', 'hypertension', 'diabetes_mellitus', 'coronary_artery_disease', 'appetite', 'pedal_edema', 'anemia']
['age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar', 'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium', 'potassium', 'hemoglobin', 'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count']

In [183]:
input_df[cat] = simple_imputer.fit_transform(input_df[cat])

In [184]:
input_df[num] = knn_imputer.fit_transform(input_df[num])

In [185]:
input_df

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,hemoglobin,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia
0,48.0,80.0,1.02,1.0,0.0,normal,normal,notpresent,notpresent,121.0,...,15.4,44.0,7800.0,5.2,yes,yes,no,good,no,no

In [186]:
for col in cat:
    input_df[col] = encoders[col].transform(input_df[col])

In [187]:
input_df

,age,blood_pressure,specific_gravity,albumin,sugar,red_blood_cells,pus_cell,pus_cell_clumps,bacteria,blood_glucose_random,...,hemoglobin,packed_cell_volume,white_blood_cell_count,red_blood_cell_count,hypertension,diabetes_mellitus,coronary_artery_disease,appetite,pedal_edema,anemia
0,48.0,80.0,1.02,1.0,0.0,1,1,0,0,121.0,...,15.4,44.0,7800.0,5.2,1,1,0,0,0,0

In [188]:
## Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-1.44491754e-01,  3.07290231e-01,  4.98050497e-01,
        -2.76464432e-02, -4.34105992e-01,  3.44791414e-01,
         4.75450986e-01, -3.27515551e-01, -2.44136538e-01,
        -3.89244650e-01, -3.93147601e-01, -3.02138732e-01,
        -1.39412253e+01, -1.47829622e+00,  9.87964728e-01,
         5.59531703e-01,  8.88174862e+03,  5.51053805e-01,
         1.36277029e+00,  1.38169856e+00, -3.03562466e-01,
        -5.19462482e-01, -4.70504034e-01, -4.09735539e-01]])

In [189]:
## PRedict churn
prediction=rfmodel.predict(input_scaled)
prediction

array([0])

In [190]:
prediction_proba = rfmodel.predict_proba(input_scaled)[0][1]
prediction_proba

0.23