In [59]:
import pickle
import pandas as pd
import  warnings
warnings.filterwarnings('ignore')

In [60]:
input_data={
"N_Days":400,
"Drug":"D-penicillamine",
"Age":21464,
"Sex":"F",
"Ascites":"Y",
"Hepatomegaly":"Y",
"Spiders":"Y",
"Edema":"Y",
"Bilirubin":14.5,
"Cholesterol":261,
"Albumin":2.6,
"Copper":156,
"Alk_Phos":1718,
"SGOT":137.95,
"Tryglicerides":172,
"Platelets":190,
"Prothrombin":12.2,
"Stage":4,
}

input_df=pd.DataFrame([input_data])
input_df

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,400,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.6,156,1718,137.95,172,190,12.2,4

In [61]:
input_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N_Days         1 non-null      int64
 1   Drug           1 non-null      object
 2   Age            1 non-null      int64
 3   Sex            1 non-null      object
 4   Ascites        1 non-null      object
 5   Hepatomegaly   1 non-null      object
 6   Spiders        1 non-null      object
 7   Edema          1 non-null      object
 8   Bilirubin      1 non-null      float64
 9   Cholesterol    1 non-null      int64
 10  Albumin        1 non-null      float64
 11  Copper         1 non-null      int64
 12  Alk_Phos       1 non-null      int64
 13  SGOT           1 non-null      float64
 14  Tryglicerides  1 non-null      int64
 15  Platelets      1 non-null      int64
 16  Prothrombin    1 non-null      float64
 17  Stage          1 non-null      int64
dtypes: float64(4), int64(8), object(6)
memory usage: 272.0+ bytes

In [62]:
cat=[]
num=[]
for i in input_df.columns:
    if input_df[i].dtype=="object":
        cat.append(i)
    else:
        num.append(i)
print(cat) 
print(num)

['Drug', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema']
['N_Days', 'Age', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage']

In [63]:
limits = pickle.load(open("outlier_limits.pkl","rb"))

In [64]:
for col,(lower,upper) in limits.items():
    input_df[col] = input_df[col].clip(lower,upper)

In [65]:
encoders=pickle.load(open("dep_encoders.pkl","rb"))
for col in cat:
    input_df[col] = encoders[col].transform(input_df[col])

In [66]:
input_df

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,400,0,21464,0,1,1,1,2,7.3,261,2.6,156,1718,137.95,172,190,12.2,4

In [67]:
zscalar=pickle.load(open("zscaler.pkl","rb"))
input_scaled = zscalar.transform(input_df)

In [68]:
LRModel=pickle.load(open("LRModel.pkl","rb"))
prediction = LRModel.predict(input_scaled)

In [69]:
print(prediction)

[2]

In [47]:
indep_encoder=pickle.load(open("indep_encoder.pkl","rb"))
result = indep_encoder.inverse_transform(prediction)
print(result)

['D']

In [76]:
prediction_proba = LRModel.predict_proba(input_scaled)[0]
print(max(prediction_proba))

0.984267708104902