In [42]:
import pickle
import pandas as pd
import  warnings
warnings.filterwarnings('ignore')

In [43]:
input_data={'X1 transaction date':2013.500,
'X2 house age':13.3,
'X3 distance to the nearest MRT station':561.9845,
'X4 number of convenience stores':5,
'X5 latitude':24.98746,
'X6 longitude':121.54391
}

input_df=pd.DataFrame([input_data])
input_df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2013.5,13.3,561.9845,5,24.98746,121.54391

In [44]:
limits = pickle.load(open("outlier_limits.pkl","rb"))

for col,(lower,upper) in limits.items():
    input_df[col] = input_df[col].clip(lower,upper)

In [45]:
input_df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
0,2013.5,13.3,561.9845,5,24.98746,121.54391

In [46]:
scalar=pickle.load(open("scalar.pkl","rb"))
input_df_scaled=scalar.transform(input_df)
input_df_scaled

array([[ 1.18554636, -0.35267606, -0.41823645,  0.28990029,  1.49853877,
         0.69697243]])

In [47]:
model=pickle.load(open("regr.pkl", "rb"))

In [48]:
prediction = model.predict(input_df_scaled)
print(prediction)

[49.01686987]